### ISSUE TITLE
0_Unfixed_SNPs_Calling.sh: $markkept file ?

### ISSUE THREAD

**Issue by weiju** [MtbEvolution/resR_Project#4]
Hi, 
when running the unfixed SNP calling pipeline, we are running into a problem that the $markkept file
is not found.
I assumed it is a file <sample>.markkept, but that does not seem to be the case. Could you please let me
know what the file is supposed to be named and where it is generated ?

```
#extract unfixed SNPs from forup files, this will create two files: "markdisc" and "markkept"; the suspected false positives(such as mutations with tail region enrichment) will be moved to markdisc file
perl ~/script/mix_extract_0.95.pl $forup > $mix;
perl ~/script/forup_format.pl $mix > $mixfor;
perl ~/script/info_mark.pl $mixfor > $mixmark;
perl ~/script/redepin_filt.pl Excluded_loci_mask.list $dep $mixmark

```

**Comment by weiju** [comment]
These are the lines of the script that are troublesome because of the missing $markkept file:

```
perl ~/script/unfix_scripts/repeatloci_filter.pl 5up_remove_loc.list $markkept > $keptfilt
#annotation of unfixed SNPs
cut -f9-11 $keptfilt > $keptsnp
perl ~/script/1_MTBC_Annotation_mtbc_4411532.pl $keptsnp > $keptanofilt
```

Thanks !

**Comment by MtbEvolution** [comment]
"perl ~/script/redepin_filt.pl Excluded_loci_mask.list $dep $mixfor” should create two files including “markkept” and “markdisc”.

On Dec 15, 2023, at 14:22, Wei-ju Wu ***@***.******@***.***>> wrote:



These are the lines of the script that are troublesome because of the missing $markkept file:

perl ~/script/unfix_scripts/repeatloci_filter.pl 5up_remove_loc.list $markkept > $keptfilt
#annotation of unfixed SNPs
cut -f9-11 $keptfilt > $keptsnp
perl ~/script/1_MTBC_Annotation_mtbc_4411532.pl $keptsnp > $keptanofilt


Thanks !

**Comment by weiju** [comment]
Thanks, now it makes sense !
