### ISSUE TITLE
Unfixed pipeline: 1_MTBC_Annotation_mtbc_4411532.pl : hard-coded paths

### ISSUE THREAD

**Issue by weiju** [MtbEvolution/resR_Project#5]
Hi, I just wanted to let you know that the script 1_MTBC_Annotation_mtbc_4411532.pl contains hardcoded paths

```
open F1, "</n/home07/edwin/script/translate/mtbc_translate/2_Tuberculist_new_20150307" or die $!; #open Tuberculist_new_20150307
```
...
```
open F2, "</n/home07/edwin/script/translate/mtbc_translate/3_genetic_codes" or die $!; #open genetic_code
```
...
```
open F3, "</n/home07/edwin/script/translate/mtbc_translate/4_mtbc_sequence.fasta" or die $!; #open genome.fasta
```
Since they refer to files within the project I was able to adjust the path, but I think it would be easier to keep the paths outside the Perl file.

Thank you !

**Comment by MtbEvolution** [comment]
Hi,

Just simply replace those with the directory paths of your own.

Qingyun

On Dec 15, 2023, at 15:22, Wei-ju Wu ***@***.******@***.***>> wrote:



Hi, I just wanted to let you know that the script 1_MTBC_Annotation_mtbc_4411532.pl contains hardcoded paths

open F1, "</n/home07/edwin/script/translate/mtbc_translate/2_Tuberculist_new_20150307" or die $!; #open Tuberculist_new_20150307


...

open F2, "</n/home07/edwin/script/translate/mtbc_translate/3_genetic_codes" or die $!; #open genetic_code


...

open F3, "</n/home07/edwin/script/translate/mtbc_translate/4_mtbc_sequence.fasta" or die $!; #open genome.fasta


Since they refer to files within the project I was able to adjust the path, but I think it would be easier to keep the paths outside the Perl file.

Thank you !
